### ISSUE TITLE
Enable Zoom of RIP Documents

### ISSUE THREAD

**Issue by christianvozar** [cwensley/pablodraw#17]
## Issue

Pablo (appears to, correct if wrong) employs a strict RIPscrip specification locking the drawing view port to 640x300 (as per the RIP specification). However, on high resolution monitors (which is anything made after 1998, ha!) this drawing canvas is far too small to be usable for RIP drawing.

## Fix

Enable the Zoom command in RIP drawing to utilize a multiplier. There is no getting away from the static magic numbers that RIP employs for it's specification but if we could multiple by 2 or even 4, then during file save reduce the zoom of the canvas we could drive a lot more adoption of RIP graphics with Pablo.

**Comment by cwensley** [comment]
This is now enabled in the latest [alpha release](https://github.com/cwensley/pablodraw/releases/tag/3.3.0-alpha1).  Give it a try!  Both the animation and editing can be done while zoomed.  Before, zooming only worked in view mode after animation was finished.
