### ISSUE TITLE
iCE Colors Enabled by Default

### ISSUE THREAD

**Issue by christianvozar** [cwensley/pablodraw#21]
This behavior leads to iCE colors enabled for an ansi file on save even if the original artists intention isn't to use them. By default PabloDraw should start a new file with ice colors disabled with the user needing to intentionally turn this feature flag on. This will lead to more accurate sauce information/file saves for ansi files.

**Comment by cwensley** [comment]
Thanks for the issue.  If you turn iCE Colors off _before_ editing a file, it will remember that as the default for the next time.  I agree it's probably best to make the default off.  It won't change your settings as you have to change it yourself or delete the settings file.
