### ISSUE TITLE
32bit Applications no longer supported by MacOS >=10.15

### ISSUE THREAD

**Issue by andyherbert** [cwensley/pablodraw#24]
<img width="532" alt="Screenshot 2019-10-08 at 10 20 09" src="https://user-images.githubusercontent.com/25620/66402074-1b344c80-e9dc-11e9-9512-362a0970e2d1.png">

I assume that 32 bit support for applications won't be making a return to MacOS.

**Comment by cwensley** [comment]
Thanks for reporting the issue, @andyherbert.  I'll work to get it recompiled in 64-bit.

**Comment by dyurchuk** [comment]
Thank you, I love this program! Thanks for your hard work.

**Comment by LimpingNinja** [comment]
Adding in a voice to this request.

**Comment by fhemberger** [comment]
FWIW, I went through the struggle to download 10 GB of Visual Studio and XCode, find the missing packages not shipped/linked with this repo and and managed to compile a 64bit version of the current unreleased `v3.3.0`, which seems to work fine on macOS Catalina. 🎉

**Of course** this version is not digitally signed for release, unsupported and comes with no warranty. But maybe it helps while waiting for the official release to come out:

[PabloDraw-3.3.0-dev-macOS-64bit.zip](https://github.com/cwensley/pablodraw/files/4184354/PabloDraw-3.3.0-dev-macOS-64bit.zip)

@cwensley It would be awesome if you could compile an official version (even if you tag it as pre-release) and add the binaries to the GitHub release.

**Comment by dyurchuk** [comment]
Nice work! Very cool of you! Seems to work well on my Macbook Pro in Catalina 10.5. Will let you know if I experience any issues on my end!

**Comment by hakluke** [comment]
@fhemberger thank you so much for this!

**Comment by teikko** [comment]
@fhemberger After upgrading to Big Sur that no longer works.

**Comment by fhemberger** [comment]
@teikko This was always just meant as a temporary solution. Please ask @cwensley to release a new version with proper support for Catalina and Big Sur.

**Comment by cwensley** [comment]
Hey guys, I've got new test builds that should fix this issue.  Give it a try! 

https://github.com/cwensley/pablodraw/releases/tag/3.3.0-alpha1

**Comment by cwensley** [comment]
Closing this as fixed.  3.3.0 should be released soon!  In the meantime, give the above a go.
