### ISSUE TITLE
Having Build Troubles on Windows and Raspberry Pi 3B+

### ISSUE THREAD

**Issue by JohnnyErnest** [cwensley/pablodraw#26]
Hope everything's going well Curtis! I used to talk to you on #ansi on EFNet, I was building a BBS/CMS called Psylent that I may be picking back up, but I'm also developing a database platform and web backend similar to Django for .NET Standard that I'm hoping to get out on Github soon. 

I want to build Pablodraw from source on Windows 10 and on Raspbian and use that as an example for building some cross-platform apps. I'll have to build from source for the RPI since it's running ARM.

I'm running into troubles with VS2019 needing Mono.Nat and Lidgren.Network. So I try to install via the Package Manager Console in VS2019 on Windows and get this, see image 3:

<img width="960" alt="PablodrawError" src="https://user-images.githubusercontent.com/25945156/81241758-d18efd00-8fd0-11ea-99d7-6c69b9faed5f.png">

<img width="960" alt="PablodrawError2" src="https://user-images.githubusercontent.com/25945156/81241969-76113f00-8fd1-11ea-9531-f1b6ca3dc44b.png">

<img width="960" alt="PablodrawError3" src="https://user-images.githubusercontent.com/25945156/81242099-e029e400-8fd1-11ea-9590-10c6cbb67eef.png">

What I ended up doing to build on Windows was to remove the Mono.Nat and Lidgren projects, and then install the packages in the projects where needed via NuGet, but do you happen to know what's going on with the yellow triangles on the dependencies? 

Also I had to disable the Mac project for it to build on Windows or VS2019 errors.

<img width="960" alt="PablodrawError4" src="https://user-images.githubusercontent.com/25945156/81243106-84ad2580-8fd4-11ea-9db7-ace121a3b1f9.png">

Still haven't gotten it to build on the Raspberry Pi yet. Everything has to be built from source on the Pi just about. 

I'm also looking to develop apps with Eto Forms. Here at home I've got a MacBook Pro (2015), a Windows 10 desktop and laptop, and a Raspberry Pi 3 B+ for testing, also a developer unlocked Barnes & Noble Nook running an older version of Android.

When I try to run msbuild on the Pi I get a lot of errors with it wanting MonoMac. I can log it on a separate ticket for feature enhancement on the Eto repository if you want.

**Comment by JohnnyErnest** [comment]
I managed to get Pablo running on the RPI 3 B+ just by using the compiled build from Windows and running "mono PabloDraw.exe", although I haven't managed to get a native build on the RPI itself yet.

Lots of these warning messages come up though, it looks like the gdk and cairo dependencies have some issues with them.

<img width="960" alt="PablodrawError5" src="https://user-images.githubusercontent.com/25945156/81248854-ed9b9a00-8fe2-11ea-84dc-ec03043032bf.png">

**Comment by cwensley** [comment]
@JohnnyErnest I think what might be going on is the submodules aren't initialized when cloning the repo. You can see a few examples [here](https://stackoverflow.com/a/4438292/981187) how to do that.

Note that downloading a .zip archive of the source does not include the submodules.

**Comment by JohnnyErnest** [comment]
That got PabloDraw working from build on both Windows and the Raspberry Pi.

There's one more issue getting Eto to work from build on the RPI 3 B+, I encountered a Garbage Collector memory error during build.

<img width="960" alt="EtoError1" src="https://user-images.githubusercontent.com/25945156/81339765-4cf5ba80-9074-11ea-94ca-405e601a1e33.png">

**Comment by JohnnyErnest** [comment]
I'll close this issue and open a new one on the Eto repository.
