### ISSUE TITLE
missing parts when saving after changing colors to newly added custom color

### ISSUE THREAD

**Issue by neo-backwards-one** [cwensley/pablodraw#31]
# PabloDraw3.3.0-alpha1 on windows 10 (1909)

upon changing some of the original colors, the newly saved .ans file is missing bits and pieces as seen in the pictures. 

i included the .ans files although since i stripped it down to the small region of the screenshot, these might
not be in their state when the issue originally occured. the original files can be provided if needed.

changed colors are indicated as 01, 02 and 03 in the pictures 01_a.png and 01_b.png

| before | after | delta |
|- |-  |-  |
| [01_a.zip](https://github.com/cwensley/pablodraw/files/5905939/01_a.zip) (original .ans)        | [01_b.zip](https://github.com/cwensley/pablodraw/files/5905940/01_b.zip) (original .ans)           | no file included  |
| ![01_a](https://user-images.githubusercontent.com/78374580/106501933-04b0df00-64c4-11eb-8967-55cfe8abcb69.png)      | ![01_b](https://user-images.githubusercontent.com/78374580/106501964-0e3a4700-64c4-11eb-898e-4dcd4fa43c41.png) | ![01_c](https://user-images.githubusercontent.com/78374580/106501971-11353780-64c4-11eb-86c9-94cd51806851.png) |
| 01 | 01 | - |
| hue: 160 | hue: 160 | - |
| sat:   0 | sat:   0 | - |
| bri: 161 | bri:  82 | - |
|   r: 171 |   r:  87 | - |
|   g: 171 |   g:  87 | - |
|   b: 171 |   b:  87 | - |
| 02 | 02 | - |
| hue: 160 | hue: 160 | - |
| sat:   0 | sat:   0 | - |
| bri:  82 | bri:  52 | - |
|   r:  87 |   r:  55 | - |
|   g:  87 |   g:  55 | - |
|   b:  87 |   b:  55 | - |
| 03 | 03 | - |
| hue: 160 | hue: 160 | - |
| sat:   0 | sat:   0 | - |
| bri:  52 | bri:  42 | - |
|   r:  55 |   r:  45 | - |
|   g:  55 |   g:  45 | - |
|   b:  55 |   b:  45 | - |

additionally:
since i am not sure if this is the cause of the issue in hand i included the newly added custom colors to the palette
as follows (these are all additions, the original colors are untouched):

| 01 | 02 | 03 | 04 | 05 |
| - | - | - | - | - |
| hue: 139 | hue: 140 | hue: 109 | hue: 110 | hue: 160 |
| sat:  28 | sat:  30 | sat:  39 | sat:  42 | sat:   0 |
| bri:  60 | bri:  74 | bri: 107 | bri: 136 | bri:  52 |
|   r:  56 |   r:  69 |   r:  95 |   r: 125 |   r:  55 |
|   g:  64 |   g:  79 |   g: 132 |   g: 164 |   g:  55 |
|   b:  71 |   b:  89 |   b: 122 |   b: 154 |   b:  55 |

**Comment by cwensley** [comment]
Hey @neo-backwards-one, thanks a ton for filing the issue!  Looks like it was because the logic to find the end of the line ignored spaces with color 8 as background, which is obviously incorrect.
