### ISSUE TITLE
Issue with Pablo Console Immediately Exiting

### ISSUE THREAD

**Issue by christianvozar** [cwensley/pablodraw#33]
I was working on getting Pablo to run inside a Docker container; doing so would let me run several pablo servers on the same hardware with minimal effort. Docker assumes that the application running in the container is running in the foreground and awaiting a SIGQUIT (or other sig) to exit, otherwise it just sits there without exiting.

For some reason when Pablo executes in a container it always immediately exits and I'm not sure why. Is there any way to upgrade the console app to explicitly await for a CTRL-C or other combination so that it sits in the foreground and awaits? I know that it currently does that with CTRL-Z (I think) but when I've tried to do this it always exits immediately.

```
mono /usr/local/bin/PabloDraw.Console.exe -p=gtk --server --port=14400 --file=/usr/local/bin/ansi/server-joint.ans -op=admin -pw=pablorocks -ul=editor --autosave=60 --backup --text-ice=false --text-use9x=false
```

**Comment by cwensley** [comment]
I'll try to look into this when getting the console compiled for .NET 5 native executables.  Thanks for reporting the issue!

**Comment by christianvozar** [comment]
Happy to test with Docker if you get a build you think is ready. I think some simple docker instructions on running it would be useful and I could handle that in a Readme.

**Comment by cwensley** [comment]
I'm not quite sure, but the [3.3.0-beta1](https://github.com/cwensley/pablodraw/releases/tag/3.3.0-beta1) might change how this works, please give it a try and let me know!

**Comment by cwensley** [comment]
Closing this as mono is no longer involved.  Please let me know if there's still issues with 3.3.x or above.
