### ISSUE TITLE
old filename shown in window title bar when saving as different filename

### ISSUE THREAD

**Issue by neo-backwards-one** [cwensley/pablodraw#34]
# PabloDraw3.3.0-alpha1 on windows 10 (1909)

whenever saving as a new filename, the old filename will be shown in the windows title bar.

this is confusing when you're working with several versions, as you don't know which actual file is active in the current window and what implications it has to the normal saving behaviour (ctrl + s).

**Comment by ericolito** [comment]
I can confirm this. This bug also occurs in 3.2.1.

**Comment by cwensley** [comment]
Hm, I really need to separate some of the formats in "save as" into  "export", where "export" would be anything like gif/jpeg/etc.  Thanks for reporting the issue.
