### ISSUE TITLE
Edit functions not availible in 3.3.0-alpha3 Pre-release for Linux

### ISSUE THREAD

**Issue by ericolito** [cwensley/pablodraw#47]
Can't edit block edit mode with alt+b, neither use the edit functions. See screenshot below.

https://skapar.com/~hellbeard/pablodraw.png

**Comment by cwensley** [comment]
This should now be fixed with [beta1](https://github.com/cwensley/pablodraw/releases/tag/3.3.0-beta1), please give it a try!
