### ISSUE TITLE
[macOS] regression: 3.3 beta versions don't have version numbers

### ISSUE THREAD

**Issue by core-code** [cwensley/pablodraw#85]
both CFBundleVersion and CFBundleShortVersionString are missing from the Info.plist file, e.g. affecting "Get Info", "Column View" and "Quick Look":

<img width="264" alt="Screenshot 2023-03-12 at 18 40 36" src="https://user-images.githubusercontent.com/1261954/224562415-021479a2-3b89-4994-8409-882f64ebc793.png">

**Comment by cwensley** [comment]
Ah, thanks for pointing that out!  I'll try to get that fixed up.

**Comment by core-code** [comment]
thanks!
