### ISSUE TITLE
Brush Editor opens up when clicking on every button.

### ISSUE THREAD

**Issue by SoundCrafterYT** [cwensley/pablodraw#89]
I was trying to make my first ANSI text screen and I tried to setup the brush. Everytime I click on a different button, the brush editor opens up and no cursor changes whatsoever. Even minimizing the window opens up the brush editor.

**Comment by cwensley** [comment]
Hey @SoundCrafterYT, thanks for reporting the issue.  What version are you using?

**Comment by SoundCrafterYT** [comment]
The latest version from this site

**Comment by cwensley** [comment]
sooo.... 3.3.12-beta?  Sorry but it really helps if you are explicit.  Also, do you have exact steps to reproduce the issue?  What button(s) exactly are you pressing and in what order?  Any additional information would help greatly.

**Comment by SoundCrafterYT** [comment]
I was first clicking on the File > New to make a new Text page. Then I clicked on the text tool to see if the program actually works on this one. After that, I wanted to start making things with the Brush Editor. I chose the color and the character I wanted, then the whole window became the brush editor (Including its taskbar button).
